// Central list of fonts available in the editor (Create + Admin Upload Frame).
// NOTE: Custom fonts require corresponding @font-face declarations and font files.

export const EDITOR_FONT_FAMILIES = Object.freeze([
  // Google Fonts (loaded via my-app/index.html)
  "Inter",
  "Plus Jakarta Sans",
  "Manrope",
  "DM Sans",
  "Urbanist",
  "Mulish",
  "Outfit",
  "Red Hat Display",
  "Lexend",
  "Public Sans",
  "Figtree",
  "DM Serif Display",
  "Fraunces",
  "Spectral",
  "Lora",
  "Crimson Pro",
  "Alegreya",
  "Bodoni Moda",
  "Cormorant Infant",
  "Archivo Black",
  "Space Grotesk",
  "Syne",
  "Unbounded",
  "Sacramento",
  "Allura",
  "Dancing Script",
  "Satisfy",
  "Caveat",
  "Patrick Hand",
  "Archivo Narrow",
  "Encode Sans",
  "IBM Plex Sans Condensed",
  "Barlow Condensed",
  "Saira Condensed",
]);
