#!/usr/bin/env bash
set -euo pipefail

# ================================================
# Instant Midtrans Sandbox Setup (Fremio)
# - Configures backend Midtrans env vars on a remote server via SSH
# - Configures frontend local Vite env vars for Snap Sandbox
#
# Usage:
#   bash scripts/instant-midtrans-sandbox.sh
#
# Requirements:
# - You can SSH as root to the server (SSH key recommended)
# - Remote server has pm2 installed and backend deployed in /var/www/fremio-backend
# ================================================

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

DEFAULT_HOST="72.61.210.203"
DEFAULT_BACKEND_DIR="/var/www/fremio-backend"
DEFAULT_PM2_NAME="fremio-api"
DEFAULT_FRONTEND_URL="http://localhost:5180"
DEFAULT_PROXY_TARGET="https://api.fremio.id"

read -r -p "Server host/IP [${DEFAULT_HOST}]: " SERVER_HOST
SERVER_HOST="${SERVER_HOST:-$DEFAULT_HOST}"

read -r -p "Backend dir on server [${DEFAULT_BACKEND_DIR}]: " BACKEND_DIR
BACKEND_DIR="${BACKEND_DIR:-$DEFAULT_BACKEND_DIR}"

read -r -p "PM2 process name [${DEFAULT_PM2_NAME}]: " PM2_NAME
PM2_NAME="${PM2_NAME:-$DEFAULT_PM2_NAME}"

read -r -p "FRONTEND_URL for callbacks [${DEFAULT_FRONTEND_URL}]: " FRONTEND_URL
FRONTEND_URL="${FRONTEND_URL:-$DEFAULT_FRONTEND_URL}"

read -r -p "Vite proxy target (backend base URL) [${DEFAULT_PROXY_TARGET}]: " PROXY_TARGET
PROXY_TARGET="${PROXY_TARGET:-$DEFAULT_PROXY_TARGET}"

# Midtrans keys (Sandbox)
read -r -p "MIDTRANS_CLIENT_KEY (Sandbox): " MIDTRANS_CLIENT_KEY
read -s -r -p "MIDTRANS_SERVER_KEY (Sandbox, hidden): " MIDTRANS_SERVER_KEY
printf "\n"

if [[ -z "${MIDTRANS_CLIENT_KEY}" || -z "${MIDTRANS_SERVER_KEY}" ]]; then
  echo "ERROR: Midtrans keys cannot be empty." >&2
  exit 1
fi

# 1) Write frontend env locally (Vite reads .env.local automatically)
FRONTEND_ENV_FILE="$ROOT_DIR/my-app/.env.local"
cat > "$FRONTEND_ENV_FILE" <<EOF
# AUTO-GENERATED by scripts/instant-midtrans-sandbox.sh
# Localhost frontend -> Sandbox Midtrans -> Remote backend via Vite proxy

VITE_BACKEND_MODE=vps
VITE_USE_VPS=true

# Keep browser calls same-origin; Vite dev server proxies /api to backend
VITE_API_URL=/api
VITE_PROXY_TARGET=${PROXY_TARGET}

# Midtrans Snap (Sandbox)
VITE_MIDTRANS_CLIENT_KEY=${MIDTRANS_CLIENT_KEY}
VITE_MIDTRANS_IS_PRODUCTION=false
EOF
chmod 600 "$FRONTEND_ENV_FILE" || true

echo "✅ Wrote frontend env: $FRONTEND_ENV_FILE"

# Helper: base64 encode without newlines
b64() { printf %s "$1" | base64 | tr -d '\n'; }

MIDTRANS_CLIENT_KEY_B64="$(b64 "$MIDTRANS_CLIENT_KEY")"
MIDTRANS_SERVER_KEY_B64="$(b64 "$MIDTRANS_SERVER_KEY")"
FRONTEND_URL_B64="$(b64 "$FRONTEND_URL")"

# 2) Upsert backend env on remote server and restart PM2
# NOTE: This updates/creates $BACKEND_DIR/.env but only touches the Midtrans + FRONTEND_URL lines.

echo "🔧 Updating backend env on root@$SERVER_HOST ..."

ssh -o StrictHostKeyChecking=no "root@${SERVER_HOST}" \
  "BACKEND_DIR='${BACKEND_DIR}' PM2_NAME='${PM2_NAME}' \
  MIDTRANS_CLIENT_KEY_B64='${MIDTRANS_CLIENT_KEY_B64}' \
  MIDTRANS_SERVER_KEY_B64='${MIDTRANS_SERVER_KEY_B64}' \
  FRONTEND_URL_B64='${FRONTEND_URL_B64}' \
  bash -s" <<'REMOTE'
set -euo pipefail

BACKEND_DIR="${BACKEND_DIR}"
PM2_NAME="${PM2_NAME}"
ENV_FILE="$BACKEND_DIR/.env"

mkdir -p "$BACKEND_DIR"
touch "$ENV_FILE"

decode() { printf %s "$1" | base64 -d; }
MIDTRANS_CLIENT_KEY="$(decode "$MIDTRANS_CLIENT_KEY_B64")"
MIDTRANS_SERVER_KEY="$(decode "$MIDTRANS_SERVER_KEY_B64")"
FRONTEND_URL="$(decode "$FRONTEND_URL_B64")"

upsert() {
  local key="$1"
  local value="$2"

  if grep -qE "^${key}=" "$ENV_FILE"; then
    sed -i "s|^${key}=.*|${key}=${value}|" "$ENV_FILE"
  else
    printf "%s=%s\n" "$key" "$value" >> "$ENV_FILE"
  fi
}

upsert "MIDTRANS_IS_PRODUCTION" "false"
upsert "MIDTRANS_SERVER_KEY" "$MIDTRANS_SERVER_KEY"
upsert "MIDTRANS_CLIENT_KEY" "$MIDTRANS_CLIENT_KEY"
upsert "FRONTEND_URL" "$FRONTEND_URL"

chmod 600 "$ENV_FILE" || true

cd "$BACKEND_DIR"

if pm2 describe "$PM2_NAME" >/dev/null 2>&1; then
  pm2 restart "$PM2_NAME" --update-env
else
  pm2 start server.js --name "$PM2_NAME" --update-env
fi

pm2 save || true

echo "✅ Remote env updated: $ENV_FILE"
echo "✅ PM2 restarted: $PM2_NAME"
REMOTE

echo "\nDone. Next:" 
echo "1) Start frontend: cd my-app && npm install && npm run dev" 
echo "2) Watch backend logs: ssh root@${SERVER_HOST} 'pm2 logs ${PM2_NAME} --lines 100 --nostream'" 
echo "3) Test flow: Pricing -> Beli -> Snap popup" 
